broadinstitute/scp-ingest-pipeline

scripts/scratch_query/firestore_query.py
This CLI queries the Firestore cell_metadata collection to show successful ingest of Alexandria metadata. Provided pairs of known-good sets of metadata,value information, this CLI will determine the set of studies that match all provided criteria.
```
python firestore_query.py --query species__ontology_label,"Homo sapiens" --query is_living,yes --query sex,female
Studies with cells where species__ontology_label is Homo sapiens : {'SCP666', 'SCP777', 'SCP888'}
Studies with cells where is_living is yes : {'SCP777', 'SCP888'}
Studies with cells where sex is female : {'SCP666', 'SCP777'}
++++++++++++++++++++
Studies with cells matching all criteria: {'SCP777'}
```
Caveats:
• using cell_metadata collection requires OR logic which is implemented in Python and not via Firestore query
• cells …
=> Query Firestore using CLI - demo only

ingest/cell_metadata.py, ingest/clusters.py, ingest/ingest_files.py
[PR 25](https://github.com/broadinstitute/scp-ingest-pipeline/pulls?q=is%3Apr+is%3Aclosed) introduced some bugs into master. Particularly,  the "points", "cluster_type" field values in the cluster model were being populated incorrectly. Also, the document and subdocument names needed to be swapped around. This PR provides quick fixes.
=> Bug fixes for Cluster data model

.pre-commit-config.yaml
This integrates the existing hook setup (which uses the 'pre-commit' framework) with the pre-commit functionality we would expect from git-secrets. See https://github.com/broadinstitute/single_cell_portal_configs/tree/sl-git-secrets/developer-setup/git-secrets for more context.
=> pre-commit hooks expect git-secrets [SCP-1905]

Dockerfile, ingest/ingest_pipeline.py
This PR unblocks SCP-1944, SCP-1941 and other tickets in progress by:
- correcting a typo in the dockerfile so calls to python will succeed
- making metadata convention available in a public bucket in SCP prod environment
- pointing `ingest_pipeline.py` to use the newly available convention file
- also, update `scp-ingest-service` in dockerfile to `scp-ingest-pipeline`
This fulfills [SCP-1994](https://broadworkbench.atlassian.net/browse/SCP-1994)
=> Provide metadata convention in public bucket [SCP-1994]

ingest/annotations.py, ingest/cell_metadata.py, ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py, scripts/scratch_query/get_bq_job_info.py, setup.py
This PR leverages existing code for metadata validation to generate an NDJSON file suitable for upload to BigQuery.
To upload metadata, ingest-pipeline.py expects:
• the `--validate-convention` flag
• a valid BigQuery dataset name for the GCP project in the runtime environment
• a valid BigQuery table in the provided BigQuery dataset
`--validate-convention` without `--bq-dataset` and `--bq-table` will validate without uploading convention metadata to BigQuery.
This PR fulfills [SCP-1941](https://broadworkbench.atlassian.net/browse/SCP-1941)
=> Write convention metadata to BigQuery [SCP-1941]

ingest/clusters.py, ingest/dense.py, ingest/expression_files.py, ingest/ingest_pipeline.py, ingest/mtx.py, ingest/subsample.py, setup.py
This adjusts imports and packaging to ensure metadata validation code in Ingest Pipeline can be used by the public CLI.  Such adjustments are needed by broadinstitute/single_cell_portal#84; see there for more context.
This satisfies SCP-1913.
=> Adjust imports and packaging for public CLI [SCP-1913]

ingest/annotations.py
This is a patch to ensure that cell metadata files that may only have one annotation type (group or numeric, not both) can be ingested.  This avoids the pandas 'KeyError' exception.
=> check for existence of group/numeric annotations before assignment

ingest/annotations.py, ingest/cell_metadata.py, ingest/clusters.py, ingest/dense.py, ingest/expression_files.py, ingest/ingest_files.py, ingest/ingest_pipeline.py, ingest/monitor.py, ingest/subsample.py, tests/test_annotations.py, tests/test_ingest_files.py
This PR allows R formatted gene expression files to be ingested. 
Also, support for txt files has been corrected. Prior, there was no way to determine if a .txt file was tab or comma delimited.  Because of this bug, when opening a .txt file, pandas could not format the dataframe properly.  This affected dense expression mtx, cluster, and cell metadata files.
=> Ingest R formatted gene expression files

ingest/ingest_files.py, ingest/ingest_pipeline.py
This small PR addresses two bugs found in testing expression matrix ingest:
1. successful parsing of dense expression matrix ended in exit status 1
2. ingest of tsv format dense expression matrices resulted in python errors
Notes: 
took expression_matrix_example_gzipped.txt.gz, uncompressed it, opened in Excel, saved as csv and tested csv ingest to confirm that it passes. For this simple csv file derived from a "known good" single_cell_portal_core test file, csvDialect (with csv.QUOTE_NONNUMERIC removed as for tsvDialect - to fix bug #2 above) seems ok. Unclear whether the escapechar parameter is needed for csvDialect - it is not present in tsvDialect.
also pulled ea-test-ingest-files 27641e5 into this branch and ran all tests (which passed) then reverted my branch to keep this small PR …
=> expression matrix ingest bugfixes

ingest/dense.py
Correctly setting the name of expression data arrays to allow MongoDB to retrieve data when visualizing expression data in SCP.
=> using case-sensitive gene name to set data_array names for expression

ingest/mtx.py, tests/test_ingest.py
This fixes a bug in handling remote gene files and barcode files in an MTX bundle.
In addition to a new automated test, I've also verified the fix using files in our test data bucket.
This satisfies SCP-2042.
=> Support ingest for remote MTX bundle files (SCP-2042)

ingest/ingest_pipeline.py
Invalidly formatted cell metadata files receive terse message without remediation details:
__main___errors - ERROR - Cell metadata file format invalid
This small change restores the reporting of collected cell metadata file format errors so end users know what format issues need to be addressed.
=> restore error report on detection of invalid cell metadata file format

Dockerfile, ingest/ingest_pipeline.py
This upgrades the Docker image used on PAPI to use Python 3.7.  That is needed because our new Stackdriver Monitor code (#68) [uses `nullcontext`](https://github.com/broadinstitute/scp-ingest-pipeline/pull/68/files#diff-4799e037644be7d4de8355150394dbe6R140), which is [new in 3.7](https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext).
I've built a new Docker image with the updated `Dockerfile`, and verified that `docker run` now succeeds for it.
This satisfies SCP-2056.
=> Upgrade Docker to use Python 3.7 (SCP-2056)

ingest/validation/validate_metadata.py
Adding timeout parameter to external OLS API calls to prevent hanging, and adding sleep statements after each request to artificially throttle request rates to prevent TCP/IP dropouts.
This satisfies the first AC of [SCP-2067](https://broadworkbench.atlassian.net/browse/SCP-2067)
=> adding sleep & timeout to throttle number of concurrent OLS API calls

ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py, requirements.txt, tests/test_validate_metadata.py
Adding exponential backoff with "[full jitter](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/)" to all external calls to OLS when validating convention metadata.  Caching of retrieved ontologies has also been added to reduce the number of external API calls and speed up validation.  If all retries fail to connect (and validation is therefore impossible at the current time) then an error is reported back to ingest with a special error message denoting that an 'External service outage' has occurred.  This message will then be included in an email back to the user from the portal.
This PR satisfies [SCP-2076](https://broadworkbench.atlassian.net/browse/SCP-2076).
=> Exponential backoff & error handling for metadata validation

requirements.txt
This comments out memory_profiler due to failed Docker build with `psutil`.  To profile memory, simply uncomment the `memory_profiler` line in `requirements.txt`, then follow instructions from #74.
Information below is simply for reference.
Failing Cloud Build, which I reproduced locally:
https://console.cloud.google.com/cloud-build/builds/42daf386-5aff-45d1-96b3-0706ea769de0?project=broad-singlecellportal-staging
Error:
```
copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.7/psutil/tests
running build_ext
building 'psutil._psutil_linux' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/psutil
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g …
```
=> Disable memory_profiler to fix Docker build (SCP-2053)

ingest/monitor.py, ingest/validation/validate_metadata.py
This modifies validation against metadata convention to use the logging functionality from monitor.py so metadata convention validation errors will be included in the errors.txt file allowing validation information to be passed to the end user in the parsing notification email.
Additionally, detection of discrepancy between the number of cells prepared for upload from the input metadata file and the number of rows inserted in the BigQuery job will now be reported in errors.txt.
This issue fulfills [SCP-2092](https://broadworkbench.atlassian.net/browse/SCP-2092).
=> capture metadata convention validation errors via logger (SCP-2092)

ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py, tests/data/issues_metadata_v1.1.3.json, tests/data/issues_ontology_v1.1.3.json
Refactored data preparation for BigQuery upload to consistently store ontology IDs using the underscore format to simplify metadata query on ontology IDs.
Additional changes include:
- additional error messaging where ingest pipeline load fails due to lack of MongoDB access
- fix lurking issue where single value arrays were not being cast to convention-specified data type
- fix lurking issue where cast_integer_type would fail if value was nan
- avoid casting nan to string because nan is indicative of missing values
- update reference json for metadata validation tests due to changes in nan handling
NOTE: current JSON Schema validation implementation REQUIRES that non-float convention metadata cannot have nan values. SCP-2137 has been created to address this unintended requirement which …
=> Regularize stored ontology IDs (SCP-2116)

.gitignore, ingest/validation/validate_metadata.py
Adding a new column so the numeric range queries can be (relatively) sane.  Picked seconds so that we don't have to deal with float rounding issues caused by dividing stuff by 3.  The math is fuzzy because there's no pure conversion from e.g. days to months, but it should be close enough for the sorts of approximate lookups our users are doing
I've tested this manually locally with the valid_no_array_v1.1.3.tsv file.  I'd love suggestions if there's a good way to incorporate this into existing automated tests.
=> adding normalized seconds column to convention metadata export

schema/README.md, schema/alexandria_convention/snapshot/2.0.0/alexandria_convention_schema.bq_schema.json, schema/alexandria_convention/snapshot/2.0.0/scp_bq_inputs.json, scripts/convention_to_bq_schema.py, scripts/serialize_convention.py, tests/test_serialize_convention.py
BigQuery schema JSON generation now automatically occurs with metadata convention JSON generation. The script expects both convention input TSV and an scp_bq_inputs.json file in a snapshots directory under schema/&lt;project&gt;_convention/snapshot.
Generate schema file using:
`python serialize_convention.py <project> <version>`
This satisfies SCP-2289
=> Put BigQuery schema under source control (SCP-2289)

ingest/ingest_files.py
The last [PR](https://github.com/broadinstitute/scp-ingest-pipeline/pull/85) submitted to correct the numeric group labels did not account for metadata conventions that have array based data. This caused ingest to throw error ``` csv.Error: Could not determine delimiter```.  To correct this, the known delimiter is passed into the CSV sniffer. 
Command used
```
python ingest_pipeline.py --study-id 5d276a50421aa9117c982845 --study-file-id 5dd5ae25421aa910a723a337 ingest_cell_metadata --cell-metadata-file /Users/eaugusti/scp-ingest-pipeline/tests/data/valid_array_v1.1.3.tsv --study-accession SCP123 --ingest-cell-metadata
```
Automated test pass. Further testing in staging will need to be conducted to verify this PR satisfies [2214](https://broadworkbench.atlassian.net/browse/SCP-2214)
=> Pass delimiter into sniffer

ingest/ingest_files.py, ingest/validation/validate_metadata.py, tests/data/issues_array_v2.0.0.json
Handle edge case where metadata file provides an __ontology_label column but does not provide values (prevent validation from making excessive EBI OLS calls due to bug by not catching this edge case).
For required metadata, JSON schema validation will fail because 'nan' is not a string - apparently supplying nan does not count as violating the "required" constraint. Note that for optional metadata, nan values are not passed in JSON Schema for validation, only a cross-check warning will be emitted.
This commit includes updates to a reference test output file so reference matches new parse behavior.
This satisfies SCP-2375
=> Handle nan __ontology_label values (SCP-2375)

.gitignore, requirements.txt, setup.py
Minor updates to publish scp-ingest-pipeline to PyPI
These changes support SCP-2471.
=> Publish scp-ingest-pipeline to PyPI (SCP-2471)

requirements.txt, setup.py
Previous build failed CI, docker container missing grpc package. Adding explicitly to requirements.txt to ensure the dependency is included in our docker image.
This supports testing SCP-2424 and SCP-2396 in staging.
=> add grpcio dependency to requirements.txt

ingest/expression_files/dense_ingestor.py
Correcting an issue where the arrays of cell names and expression values parsed for an individual gene from a dense matrix do not line up, causing the first expression value to be lost, and the final cell name to have a `nil` expression value.
This PR satisfies SCP-2656.
=> addressing off-by-one error when aligning cell names w/ scores (SCP-2656)

ingest/expression_files/dense_ingestor.py, tests/test_dense.py
When rounding expression values to 3 digits, we are unintentionally dropping the first value.  The gene name has already been removed from this list in `filter_expression_scores`, so calling `row[1:]` is not needed.
This PR satisfies SCP-2656.
=> addressing off by one error when rounding expression values (SCP-2656)

ingest/expression_files/dense_ingestor.py, ingest/expression_files/expression_files.py, tests/test_dense.py, tests/test_expression_files.py, tests/test_ingest.py
This allows reporting of the specific errors for each validation failure.
=> enabling granular error reporting for expression matrix validation (SCP-2660)

ingest/expression_files/expression_files.py, ingest/mongo_connection.py, ingest/monitor.py, setup.py
This PR fixes the query for obtaining the known cells in expression matrices within a study. In the current code, if a dense matrix is parsed after a metadata file, it will always fail validation because the query used to get the arrays of cells from other matrix files in that study contains the "all cells" arrays from metadata files.
This satisfies SCP-2674.
=> Fix query to detect duplicate cells across expression matrices within a study (SCP-2674)

ingest/clusters.py, ingest/expression_files/expression_files.py
fix
```
'DataArray' object has no attribute 'get_data_array' 
```
and 
```
5f495049421aa91245db022d.__main___errors.ingest_expression:318:None] Error caused by inserting into collection 'genes': 'MongoConnection' object is not subscriptable
```
=> Fix client and function name

ingest/ingest_pipeline.py
[1889670378](https://sentry.io/organizations/broad-institute/issues/1889670378/?project=1424198&query=is%3Aunresolved)- We're reporting when cell metadata format is valid with logger.error when it should be reported with logger.info. Because it's reported with logger.error it's being reported in sentry when it shouldn't.
=> *SCP-2746 Change logger level for cell metadata form validation

ingest/validation/validate_metadata.py, scripts/ingest_stress_test.py, tests/test_validate_metadata.py
Users of the metadata convention reported failed validation Notifier emails that had stack traces with "unexpected exit status 65 was not ignored" and no information on how to fix their metadata files.
This simple PR changes the metadata convention from using the dev_logger to using the user_logger.
The investigation for this ticket uncovered two issues:
1. ingest_pipeline is treating numeric array-based values as invalid non-numeric data and rejecting the file as format  invalid. Created SCP-2756 to deal address this problem. Tests for array-based validation did not reveal this problem because the tests were not using the newly abstracted file format checking functions.
2. running ingest_pipeline.py produces results different from validate_metadata.py because format validation has been …
=> Return metadata convention validation error messages to user (SCP-2739)

ingest/expression_files/mtx.py, ingest/validation/validate_metadata.py
Metadata validation for NCBITaxon terms began failing on 10/14. Our term validation requests were requesting validation for NCBITAXON_XXXX terms which fail. The requests are formed using the baseURI supplied by EBI OLS. When converted to a baseURI with NCBITaxon_ instead of NCBITAXON, the validation requests succeed.
This PR adds a temporary workaround to correct the invalid baseURI we're obtaining from EBI OLS.
This resolves the bug described in SCP-2820.
=> address invalid baseURI from EBI OLS for NCBITaxon (SCP-2820)

ingest/expression_files/mtx.py, ingest/make_toy_data.py, tests/test_genomes.py, tests/test_make_toy.py
Modify make_toy_data.py to generate raw count (integer expression values) synthetic data. Also, for test_make_toy and test_genomes, delete output files when tests have completed.
This work supports SCP-2535.
=> Generate raw count synthetic data (SCP-2535)

requirements.txt
pinning loompy to a newer version caused issues with cloud build. Verified that loompy is currently not needed and confirmed that --no-cache docker builds without loompy succeed locally.
=> remove loompy from requirements.txt

ingest/monitoring/metrics_service.py
An incorrect URL from ingest pipeline was causing [build errors](https://travis-ci.com/github/broadinstitute/single_cell_portal_core/builds/201355050#L2935) when releasing scp_core. This PR addresses the issue by appending the endpoint to the base URL.
=> * SCP-2796 Fix URL for Bard

ingest/expression_files/mtx.py, tests/data/mtx/bad_format_has_character.mtx, tests/data/mtx/bad_format_has_space.mtx, tests/data/mtx/mtx_character_before_data.mtx, tests/test_mtx.py
PR addresses valid MTX files with an empty comment line after the expected header causing "not enough values to unpack (expected 3, got 1)" in production.
=> * SCP-2900 Resolve "not enough values to unpack (expected 3, got 1)"

ingest/validation/validate_metadata.py
Mouse Brain Atlas uses numeric IDs for their ontology terms. To prevent name collision, it seemed prudent to uniquefy the ID using the syntax used by other ontologies - a full name comprised of an ontology shortname, separated by underscore or colon, followed by an id. We chose "MBA" to be the ontology shortname for Mouse Brain Atlas (at the time of choosing, it was not in use as a shortname for any other ontology). The longest ID in MBA is 9 digits - we requested that ids shorter than 9 digits be padded with leading zeros in the fashion of MONDO, PATO and other ontologies.
Our U19 collaborators suggested we document the reasoning above for future reference.
=> Document reasoning for Mouse Brain Atlas ID formatting for SCP ingest (SCP-2918)

ingest/expression_files/expression_files.py, ingest/mongo_connection.py
This is a solution to try and fix the batch ops error found in [zendesk](https://broadinstitute.zendesk.com/agent/tickets/54407).  There will be a .33 second wait prior to every insert. The first time the batch ops error happens for a batch, the transaction will wait 3 mins before proceeding. After the first time, exponential backoff will be in effect to try and reinsert the document.
=> Add more time in between inserts

ingest/expression_files/expression_files.py, ingest/mongo_connection.py, scripts/scratch_ingest/dense_splitter.py
During ingest of a dense matrix in [Zendesk #54407](https://broadinstitute.zendesk.com/agent/tickets/54407), the user is encountering persistent "batch ops error" issues and unable to upload their matrix file. Investigation of "batch ops error" can be found in SCP-2909. As a workaround, the file was split into smaller subfiles for ingest and manually "stitched" together on the backend.
Saving this script in a scratch space for reference. This is a one-off workaround and does not merit test coverage until/unless a durable use case becomes apparent.
This PR supports SCP-2926.
=> Script to split dense matrix to subfiles (SCP-2926)

ingest/expression_files/expression_files.py, tests/test_expression_files.py
Ingest pipeline was not querying correctly to retrieve cell values for processed files. This was causing all cell values to be returned when a raw count file was ingested first. This PR fixes the issue.
=> * SCP-2949 Fix query for processed matrices

ingest/expression_files/mtx.py, tests/mock_data/expression/matrix_mtx/AB_toy_data_toy_unsorted_mtx_models.py
The PR addresses the ```not enough values to unpack (expected 3, got 1)``` error caused by headers being present when models were being created in transform(). The error was isolated to disordered MTX files. Transform() is expecting the pointer to be where the data starts. Instead, it received the header and not the gene-barcode-expression array. This was due to sort_mtx() not passing a file whose pointer was at the top to get_gene_expression_data(). To ensure the file pointer is always at the top of the file, get_gene_expression_data() [forces the pointer to the top of the file](https://github.com/broadinstitute/scp-ingest-pipeline/blob/7a1883a9b065fce6292a135c568047d4d0e1b4eb/ingest/expression_files/mtx.py#L195) with Python's [seek …
=> * SCP-2844 Exclude commented lines from unsorted MTX files

ingest/mongo_connection.py
This PR adds randomness, or jitter, to the exponential backoff used when AutoReconnect or BulkWriteError errors happen.
=> * SCP-2910 Add jitter to exponential backoff

ingest/expression_files/expression_files.py, tests/test_expression_files.py
If a user uploads multiple expression matrices of the same "type" (e.g. raw/processed), there is currently a race condition with validating cell names that can cause both matrix files to fail ingest (although sometimes the second matrix will pass validation).  This is because `GeneExpression.get_cell_names_from_study_file_id` will see the presence of the other matrix files, but will not be able to find any cell name `DataArray` documents for these fails.  This throws a `ValueError` and fails the entire job.  The current workaround is to wait to upload the second matrix until the first has succeeded, but this is completely opaque to the end user.
This update removes that clause, and adds an upstream check to ensure that cells are parsed from any given matrix (a `ValueError` is raised if …
=> Relax cell name validation for concurrent expression matrix parses (SCP-3009, SCP-3030)

ingest/cli_parser.py, ingest/config.py, ingest/ingest_pipeline.py, ingest/monitoring/metrics_service.py, tests/test_cli_parser.py, tests/test_metrics_service.py
This PR adds user identifier in logs from Ingest Pipeline to Bard. The user ID is a unique UUID that comes from the [metrics_user_id field](https://github.com/broadinstitute/single_cell_portal_core/blob/c727832d699bbf29b897e9be52887be9c3fc3cd1/app/models/user.rb#L99) in the User model. Rails send this ID via the optional parameter ingest parameter `----user-metrics-uuid` in ingest pipeline. There's a [check](https://github.com/broadinstitute/scp-ingest-pipeline/blob/778a5bf44d1c4b5f9cf24e8e21541af54a2df876/ingest/cli_parser.py#L254) that validates the UUID. If a UUID is not supplied, the default ID is used. The default ID should technically never be used since Ingest Pipeline can only be instantiated by a signed in user. 
Here is a screenshot of user 1:
User 2:
This PR needs to be …
=> * SCP-2763 Include user identifier in logs from Ingest Pipeline to Bard

ingest/mongo_connection.py, tests/test_expression_files.py
This PR attempts to resolve the batch-ops error due to duplicate IDs by assigning another random ID and trying to re-insert. 
To test:
Find a file that already present in your Mongo instance.
On local instance of scp-ingest-pipeline try and ingest the same file with the same study and study file ID.
In ingest_files add ```self._id = < _id value in document you're truing to duplicate>```
In logs, you'll see that the batch ops error occurred. However, you'll see in Mongo the inserted document has a different id.
=> * SCP-2909 Resolve "batch ops error" with retry using new random document ID

ingest/cell_metadata.py, ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py
Stored array-valued annotations that Mongo treated as “numeric” were plotted as NaN. To allow these annotations to be visualized in SCP, we should treat the array-based numeric data as a single string, and process the annotations as though they were regular group-based metadata entries (including storing all unique values).
From data file [valid_array_v2_1.2.txt](https://github.com/broadinstitute/scp-ingest-pipeline/blob/development/tests/data/valid_array_v2.1.2.txt), the numeric array model, 'disease__time_since_onset', will look as such:
```
{'name': 'disease__time_since_onset', 'annotation_type': 'group', 'values': [], 
'study_file_id': ObjectId('5dd5ae25421aa910a723a337'), 
'study_id': ObjectId('5d276a50421aa9117c982845')}
```
**Notice how the stored 'values', as in production, are …
=> * SCP-3069 Store numeric arrays as group annotation types

ingest/__init__.py, ingest/cell_metadata.py, ingest/expression_files/mtx.py, ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py, setup.py, tests/test_cell_metadata.py, tests/test_validate_metadata.py
Tests in single_cell_portal repo fail due to Classes in the repo that were refactored earlier this year. Methods used for tests in single_cell_portal are now obsolete. To use scp-ingest-pipeline as-is in the tests, an IngestPipeline object would need to be instantiated to use the conforms_to_metadata_convention method, which is more complex than instantiating a CellMetadata object which is what the current, broken tests do. Logically, conforms_to_metadata_convention should be a CellMetadata method because none of the other ingest file types require the metadata convention. To ease the repair of tests in the single_cell_portal repo, this PR moves the conforms_to_metadata_convention method to the Cell Metadata Class.
To test (is kinda finicky right now, sorry!)
pre-test: find a study in …
=> Relocate IngestPipeline method about metadata convention to CellMetadata Class (SCP-3632)

ingest/expression_files/dense_ingestor.py
Generating dense expression matrix files incorrectly can incorporate dataframe row indices in the matrix file. When this user error occurs, the row indices become the first column of the  expression matrix and gene names end up in the second column, where gene expression values are expected, causing ingest to fail.
This PR improves upon the existing error message by passing along the offending value for easier troubleshooting.
To test, set your local instance "Ingest Pipeline Docker Image" configuration to use
`gcr.io/broad-singlecellportal-staging/scp-ingest-jlc_improve_error_msg:6b54eca `  
and upload processed matrix, using the dense matrix the file found at:
`gs://fc-2f8ef4c0-b7eb-44b1-96fe-a07f0ea9a982/test_Data/ingest_manual_test/non-numeric_dense_value.csv`  
The errror in the …
=> Improve matrix ingest error reporting (SCP-3832)

ingest/cell_metadata.py, tests/mock_data/annotation/metadata/convention/valid_array_v2_1_2.py
For visualization, numeric array-based metadata annotation values are treated as group-based values because they are string representing a series of values and not truly a numeric array. (Example: in our test file `valid_array_v2.1.2.txt`, values for disease__time_since_onset look like: '12|2', '1', '24|2', '36|3|1', '0')
Previous work, per mock data for `test_transfrom` in test_cell_metadata.py had erroneously assumed the values would not be stored. This PR restores the storage of numeric array-based metadata annotation values so they can be used in visualization.
To test: 
- set your local instance "Ingest Pipeline Docker Image" configuration to use:
gcr.io/broad-singlecellportal-staging/scp-ingest-jlc_fix_string2float:af281d0
- upload the metadata file found at: …
=> Restore storage of numeric array-based metadata annotation values (SCP-3899)

ingest/annotations.py, ingest/cell_metadata.py, ingest/clusters.py, ingest/config.py, ingest/ingest_pipeline.py, ingest/validation/validate_metadata.py, scripts/setup_mongo_dev, scripts/setup_mongo_dev.sh, tests/test_ingest.py, tests/test_metrics_service.py, tests/test_validate_metadata.py
Adding Mixpanel logging to ingest pipeline errors. This PR addresses logging of errors that use the store_validation_issue from the Annotation Class. Logging expression matrix ingest errors requires a different approach and will be addressed in follow on ticket SCP-4037.
This PR adds a "file-validation" event to Mixpanel logging upon completion of an ingest pipeline run. The event has the following properties ingest pipeline has not reported before:
- logger - always set to "ingest-pipeline"
- trigger - "sync" if study file has remote_location set
                "dev_mode" if BYPASS_MONGO_WRITES is set to "yes"
                "upload" if neither of the above are true
- status - success|failure of the ingest pipeline job
- errorTypes - aligned with errorType used in CSFV
- errors - array …
=> Log ingest annotation validation errors to Mixpanel (SCP-3921)

ingest/validation/validate_metadata.py
[Zendesk 269187](https://broadinstitute.zendesk.com/agent/tickets/269187) indicated an ingest error about float values that the study owner couldn't understand. This error turns out to be an unhandled exception where ingest did not correctly manage conventional single numeric array-based metadata values.
I've taken Constantine's metadata file and extracted just the head of the file (This avoids the content error that lurks in the file). It can be obtained at gs://fc-2f8ef4c0-b7eb-44b1-96fe-a07f0ea9a982/test_Data/manual_testing/Z269187.txt
To test: 
Configure your local instance to use docker image
`gcr.io/broad-singlecellportal-staging/scp-ingest-jlc_iterable_float_bugfix:1a92c2b `
Confirm that ingest of file Z269187.txt succeeds.
This PR resolves SCP-4060
=> Fix conventional single numeric array-based metadata value handing (SCP-4060)

README.md, ingest/annotations.py, ingest/cell_metadata.py, ingest/clusters.py, ingest/config.py, ingest/expression_files/dense_ingestor.py, ingest/expression_files/expression_files.py, ingest/expression_files/mtx.py, ingest/ingest_pipeline.py, ingest/monitoring/metrics_service.py, ingest/validation/validate_metadata.py, tests/test_dense.py, tests/test_metrics_service.py, tests/test_mtx.py, tests/test_validate_metadata.py
Adding Mixpanel logging to ingest pipeline expression matrix errors. This PR addresses logging of errors from the GeneExpression Class. 
This PR generates a "file-validation" event to mixpanel logging upon completion of an ingest pipeline expression matrix ingest.
Bugfix - with this PR file-validation events should now correctly discriminate between triggers "sync" and "upload"
Logging refinement - with this PR file-validation events will no longer report "errors" or "warnings" (but will continue to report "numErrors" and "numWarnings", where applicable) - this change avoids the loss of logging when the reported errors/warnings are too long and would trigger a Bard error instead of logging to Mixpanel
set your local Portal instance to use docker image: …
=> Adding Mixpanel logging to ingest pipeline expression matrix errors (SCP-4037)

ingest/annotations.py, ingest/clusters.py, ingest/config.py, ingest/ingest_pipeline.py, tests/data/cluster_non-numeric.txt, tests/test_cluster.py
Previously ingest validation errors during "preprocess" or subsampling were not reported to Mixpanel because the mechanisms for mixpanel reporting (accessing the Annotation Class "props" dictionary) were not accessible. ValueError issues caused premature exit of the ingest_pipeline job so these failed ingests did not report as failed file-validation events. This work also covers subsampling "Cluster file has cell names that are not present in cell metadata file" errors and "Duplicate annotation header names..." ValueError that is part of Annotation file preprocessing.
In this PR, ad-hoc props for Mixpanel reporting are used to ensure that ValueError events are logged.
To test:
1. set your local instance to use docker image:
gcr.io/broad-singlecellportal-staging/scp-ingest-jlc_log_valueerro …
=> Log ingest pipeline ValueError exceptions to Mixpanel (SCP-4139)

Dockerfile
The update of pandas in `jlc_make_data_objects` caused a cloud build failure because more recent pandas' setup.py invoke `import numpy`. In a cloud build scenario, numpy is collected but not installed when the pandas build is attempted so the pandas build fails (Older pip builds each package first before installing any packages). 
By updating pip as part of the docker install process, a more sophisticated install solver uses better order of installation to ensure numpy is available before pandas installation is attempted.
=> Update pip in docker build to resolve pandas install issue

.circleci/config.yml
test_make_toy and test_genomes reach out to NCBI and/or Ensembl. These external dependencies have lead to false positives in CI testing which slows down the development cycle. Because the functionality being testing is not used in production, let's skip these tests in CI but retain them in the codebase for internal reference.
locally, in the tests directory, you can run:
pytest -k 'not test_genomes and not test_make_toy' 
and confirm that test_make_toy and test_genomes are no longer run.
Confirm the behavior in CircleCI for the following CI runs in the `Run tests` section:
https://app.circleci.com/pipelines/github/broadinstitute/scp-ingest-pipeline/1518/workflows/98ec5329-5d4e-4721-881b-988da1b145e1/jobs/1472
https://app.circleci.com/pipelines/github/broadinstitute/scp-ingest-pipeline/1518 …
=> Update CircleCI configs to skip problematic tests (SCP-4209)

ingest/de.py, tests/test_de.py
Using a small test dataset derived from public study SCP1677, implemented an integration test for the pilot DE pipeline. This test runs the equivalent of:
> ingest_pipeline.py --study-id addedfeed000000000000000 --study-file-id dec0dedfeed0000000000000 differential_expression --annotation cell_type__ontology_label --matrix-file-path ../tests/data/differential_expression/de_integration.tsv --matrix-file-type dense --cell-metadata-file ../tests/data/differential_expression/de_integration_unordered_metadata.tsv --cluster-file ../tests/data/differential_expression/de_integration_cluster.tsv --name de_integration --study-accession SCPde --differential_expression 
and checks that expected output file "de_integration--cell_type__ontology_label--cholinergic_neuron--wilcoxon.tsv"
has the same md5 …
=> Integration test for pilot DE process (SCP-4204)

ingest/ingest_pipeline.py
This adds a general try except around all ingest code, with the hope of getting better sentry visibility into what's going on with lower level errors. 
TO TEST:
1. confirm a normal ingest runs successfully.
2. simulate a low-level DB connection initializing error by  inserting `raise NameError('Test error')` as the first line of `get_mongo_db` on line 163 of `ingest_pipeline.py`
3. add a breakpoint/log statement in `log_exception` of `monitor.py`
4. rerun an ingest, confirm breakpoint/log is triggered
=> Adding general try-except (SCP-4279)

ingest/ingest_pipeline.py
Fixes a bug where `__event_name` was read in the `exit_pipeline` function, but not set if the global exception handler was triggered.
=> Setting __event_name for unhandled errors (SCP-4279)

ingest/ingest_pipeline.py
Modifying ingest pipeline file delocalization for DE introduced a bug that causes the user_log.txt to no longer be available. Study owners are not receiving the necessary information to correct their files.
This PR restores user_log.txt delocalization so ingest errors can be delivered to study owners.
To test:
1. Start up your local instance with DelayedJob.
2. In your local instance, make sure `QA Dev Email` is set to your email address so you will receive admin notification emails for local ingest jobs.
3. Set `Ingest Pipeline Docker Image` to:
gcr.io/broad-singlecellportal-staging/scp-ingest-jlc_fix_delocalization:f67e490
4. From ingest repo, upload `scp-ingest-pipeline/tests/data/annotation/metadata/invalid_metadata_v2.0.0.tsv` as metadata file
5. Find the following email …
=> Fix ingest pipeline user_log.txt delocalization (SCP-4445)

ingest/de.py, tests/test_de.py
In SCP1288, we found that filename sanitization (converting all non-alphanumeric to underscore) could cause a problem where two cluster/annotation/group names that only differ by "+" or "-" would result in a single filename (ie. the 2nd result would clobber the first and both names would reference the same file with one name yielding incorrect data).
Example 
`groups CD16+_Monocyte` and `CD16-_Monocyte` both result in the following filename:
UMAP_Cell_Embeddings--FinalCellType--CD16__Monocyte--study--wilcoxon.tsv
Implementation:
where "+" in cluster/annotation/group names for DE, replace with "pos"
note: "-" is converted to underscore
Manual test:
activate the scp-ingest-pipeline repo virtualenv
then from the ingest directory of the scp-ingest-pipeline repo, perform this setup:
> source …
=> Distinguish between + and - in sanitized DE filenames (SCP-4533)

Dockerfile, ingest/mongo_connection.py, tests/test_discard_documents.py, tests/test_expression_files.py
Very large expression matrices (e.g. > 10 GiB) are prone to connection issues during ingest.  While the cause is not fully understood, one theory is that expression matrices with both high cell counts & high proportions of expressed cells cause timeouts when inserting into MongoDB due to the large amount of data sent to and received back from the database.  Current retry functionality has been shown to be very brittle with extremely large files, causing repeated failed ingests.
While investigating a 47 GiB matrix that failed to ingest, it was discovered that our logic for filtering out documents that may have already been inserted before the connection was dropped was faulty, and as such may not catch all potential errors.  The updated filtering methodology only matches on the document …
=> Handle existing inserts when retrying from dropped MongoDB connection (SCP-4621)

ingest/anndata_.py
When ingesting a file, I received this error:
`ValueError: Too few dimensions for visualization in obsm "X_umap", found 2, expected 2 or 3.`
The check for clustering_dimension didn't allow for just 2 (X, and Y) so just adding that.
=> Allow clustering_dimension for 2 dimensions (SCP-4828)

ingest/anndata_.py, tests/test_anndata.py
This update fixes a bug where extracted clustering files are not delocalized back to the source bucket when running `AnnData` ingest jobs.  The issue is that filenames are not correctly set and passed to downstream methods.  There is now a single place where filenames are set and this method is referenced where needed.
1. Download the h5ad file from https://cellxgene.cziscience.com/collections/2902f08c-f83c-470e-a541-e463e25e5058 and place it in any bucket that you have access to at the root folder
2. Run ingest pipeline via command line
a. Activate the scp-ingest-pipeline repo virtualenv
b. From the ingest directory of the scp-ingest-pipeline repo, perform this setup:
source ../scripts/setup_mongo_dev.sh <path to your Github token file>
3. Run the following command, pasting in the …
=> Correctly set filename when delocalizing extracted clustering files (SCP-4831)

tests/test_anndata.py, tests/test_ingest.py
This update adds full test coverage for `AnnDataIngestor`.  This will give us a working test harness moving forward that we can add to as we implement more data extraction methods to this class to ensure no regressions.
1. Pull this branch and initialize the `virtualenv` with:
```
python3 -m venv env --copies                               
source env/bin/activate
pip install -r requirements.txt
```
2. Go to the `tests` directory and run the following tests, ensuring that none fail:
(note: you will see a _lot_ of warnings that I was unable to silence, but there should be no failed tests).
```
pytest test_anndata.py
pytest test_ingest.py -k 'test_extract_cluster_file_from_anndata'
```
=> Adding test coverage for `AnnDataIngestor` (SCP-4825)

ingest/anndata_.py, ingest/cli_parser.py, ingest/ingest_pipeline.py, tests/test_anndata.py, tests/test_ingest.py
This is a "happy path" implementation of extracting metadata from h5ad. 
The "--extract-cluster" boolean is now the "--extract" flag with an array of values (currently array can contain "cluster" and/or "metadata"), which generates the specified SCP-compliant filetypes and delocalizes those intermediate files to the study bucket at _scp_internal/anndata_ingest 
Extracted files will be delocalized to a "subdirectory" (technically, the data is going into a object store so we're really just adding a segment in the file's name) named after the h5ad file's study_file_id. 
Extracted filenames follow this new structure:
<input_filetype>_frag.<file_type>.<file_type_detail>.tsv
input_filetype = h5ad_frag (replaces `anndata_segment`; other possible future types: seurat_frag, loom_frag)
file_type = …
=> Extract metadata from h5ad and delocalize ingest-intermediate files to study bucket (SCP-4823)

ingest/ingest_pipeline.py, tests/test_anndata.py, tests/test_ingest.py
This update adds test coverage for metadata extraction from h5ad files.  It also removes some now unused lines of code from `ingest_pipeline.py`.
1. Set up test environment locally from the project root with:
```
python3 -m venv env --copies
source env/bin/activate
pip install -r requirements.txt
source scripts/setup_mongo_dev.sh <path to your Github token file>
```
2. Go to the test directory and run the associated tests (the first suite should run in ~2-3s, but the second will take a few minutes to complete):
```
cd tests
pytest test_anndata.py
pytest test_ingest.py
```
Note: you will see a large amount of warnings from both suites but there should be no failures:
```
test_anndata.py .......... …
```
=> Adding test coverage for metadata extraction (SCP-4863)

ingest/expression_files/mtx.py, tests/test_mtx.py
New study owner Sisi Sarkizova reached out in [Zendesk #308520](https://broadinstitute.zendesk.com/agent/tickets/308520) because she was unable to upload her mtx file successfully. In the team [Slack discussion](https://broadinstitute.slack.com/archives/CBEHTH601/p1681241822185889) we observed that the process could detect matrices that need transposition (but we cannot automagically transpose the data for the study owner because future users of the data would expect the mtx file to have its data transposed). We also noted that Sisi likely didn't see the error email so this change is non-blocking.
This PR adds a refined error message when a transposed matrix is detected and enhances the standard feature/cell count mismatch error message. The messaging is automatically tested in test_mtx …
=> Refine mtx error messaging for transposed matrices (SCP-5073)

ingest/anndata_.py
The line to add the 'Z' dimension for a 3D clustering for an AnnData file being ingested is broken.
The line:
`headers = dim.append('Z')` is intended to set the headers variable to be the value of the array `dim` plus 'Z' for 3 dimensional clusterings. However, Python does not support this way of writing this, resulting in an error if a user tries to upload an AnnData file with a 3D clustering. This PR fixes that error.
You can test just running Python in your terminal and doing the following:
To see the error which results from the current code:
```
dim = ['NAME', 'X', 'Y']
headers = dim.append('Z')
'\t'.join(headers) + '\n'
```
you will see:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: can only join an iterable
To see that the 2D clusterings …
=> Bugfix for AnnData file upload with 3D clustering (SCP-5191)

ingest/author_de.py
Added correct natural sorting to the final file names generated from author DE. This is necessary to ensure that results can be displayed in the UI/UX, since it is sorting dependent. 
**Before**, showing sorting issue (note especially the file All_Cells_UMAP--General_Celltype--eosinophils--CSN1S1_macrophages--study--wilcoxon.tsv):
**After:**
=> Resolved sorting issue of pairwise output files for author DE (SCP-5204)

ingest/author_de.py, ingest/cli_parser.py, ingest/ingest_pipeline.py, tests/test_author_de.py
_If you haven't, please first review #321_.
---
This adds author DE support for output from [Seurat's FindAllMarkers()](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html#finding-differentially-expressed-features-cluster-biomarkers) function, which a user recently uploaded.
More generally, these changes implement flexible author DE headers to support _any_ long-header-format DE file uploaded by the user, extending [early parameterization under review](https://github.com/broadinstitute/scp-ingest-pipeline/pull/321).  This is achieved by removing hard-coded assumptions about the names and order of the input headers "gene", "group", and "comparison_group".  The "comparison_group" header is also now optional, easing upload of more-natively-formatted data from e.g. default Seurat …
=> Author DE: support Seurat and other formats, fix numerical groups (SCP-5296)

Dockerfile
This fixes failing Google Cloud Build runs, which broke due to our Docker image's base dependency `marketplace.gcr.io/google/ubuntu2004:latest` having removing `curl`.
This relates to SCP-5359.
=> Restore curl in Docker image; removed in upstream dependency (SCP-5359)

ingest/validation/validate_metadata.py
This update fixes an issue where some ontologies in OLS have non-standard URLs for the `fileLocation` configuration (like `GO` having a value of `http://purl.obolibrary.org/obo/go/extensions/go-plus.owl`).  This URL is used in queries to validate terms, and can lead to terms that should validate not being found.
1. Download the `GO_terms.tsv` testing file from our [test data bucket](https://console.cloud.google.com/storage/browser/_details/broad-singlecellportal-staging-testing-data/ols_testing/GO_terms.tsv;tab=live_object?project=broad-singlecellportal-staging)
2. Set up your local `scp-ingest-pipeline` environment, then run the command to ingest the file:
```
python ingest_pipeline.py --study-id 5d276a50421aa9117c982845 --study-file-id 5dd5ae25421aa910a723a337 ingest_cell_metadata …
```
=> Fix issue with non-standard `fileLocation` URLs (SCP-5419)

ingest/expression_files/expression_files.py, ingest/mongo_connection.py
Decreases `DataArray` batch size to `500` and increases `serverSelectionTimeoutMS` to 60s (amount of time to wait for server reconnect attempt).  Both are efforts to reduce the incidence of `Connection reset by peer` errors when ingesting very large expression matrices.  Longer timeout windows makes ingest more tolerant of disconnections, and decreasing the batch size should reduce the time it takes to insert and return, which should lower the probability of a disconnection happening.
Ingests through a local instance of SCP using [this large dense matrix slice](https://console.cloud.google.com/storage/browser/_details/broad-singlecellportal-staging-testing-data/large_matrix_files/chunk_0.tsv;tab=live_object?project=broad-singlecellportal-staging) (~3GB from a 110GB file, comprising 450 …
=> Increase server timeout, decrease DataArray batch to 500 (SCP-5429)

ingest/atac.py
This prototypes a module to enable displaying indexed fragment files from the Pipelines team in IGV in a web browser.
1.  Download fragments file from [GCP bucket](https://console.cloud.google.com/storage/browser/fc-bcc55e6c-bec3-4b2e-9fb2-5e1526ddfcd2/reference_data_dev/nemo_atac/multiome_dsp_pipelines?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
2. Run `which bgzip` and `which tabix`, to check if you have those tools installed
3. If above output reports tools are already installed -- it'd print something like `/opt/homebrew/bin/tabix`. If step 2 commands return nothing -- then run `brew install htslib`
4. Re-run step 2 to confirm tools installed
5. `cd ingest`
6. `cp -p <fragments file from GCP bucket> .`
7. `python …
=> Index ATAC-seq fragment files, enabling visualization in igv.js (SCP-5529)

scripts/pipelines-dev_multiome.qmd
Quarto notebook for generating matrix and (bad) cluster data for [sSCP391](https://singlecell-staging.broadinstitute.org/single_cell/study/SCP391).
This notebook was used to create classic SCP file types from an AnnData file to show that GEX visualizations using pipelines-dev data will work without additional production code. Feel free to try the notebook code, the ingest file [Library-8-20230710_gex.h5ad](https://console.cloud.google.com/storage/browser/_details/fc-376cd2d4-65b8-4d30-9ac8-6a52294a11ad/multiome-mouse/Library-8-20230710_gex.h5ad) is in the [dev reference bucket](https://console.cloud.google.com/storage/browser/fc-376cd2d4-65b8-4d30-9ac8-6a52294a11ad/multiome-mouse). The resulting files were uploaded to [sSCP391](https://singlecell-staging.broadinstitute.org/single_cell/stud …
=> Generate matrix data from example pipelines-dev GEX AnnData file (SCP-5611)

scripts/patchseq_counts.qmd
Quarto notebook for generating matrix data for [sSCP388](https://singlecell-staging.broadinstitute.org/single_cell/study/SCP388).
This notebook was used to create classic SCP file types from the paper's [exon and intron count files](https://data.nemoarchive.org/biccn/grant/u19_zeng/tolias/transcriptome/scell/PATCHseq/mouse/processed/counts/) based on manuscript-associated analysis code detailed in [rnaseqTools](https://github.com/berenslab/mini-atlas/blob/master/code/rnaseqTools.py). Feel free to try the notebook code using the [exon and intron count files](https://data.nemoarchive.org/biccn/grant/u19_zeng/tolias/transcriptome/scell/PATCHseq/mouse/processed/counts/) and [gene_lengths.txt](https://github.com/berenslab/mini-atlas/blob/master/data/gene_lengths.txt) as inputs. The resulting …
=> Generate matrix data from exon + intron count files (SCP-5558)

.gitignore, ingest/cas.py, requirements.txt
This is a "Hello World" for Cellarium CAS in SCP.  [Cell Annotation Service](https://www.cellarium.ai/tool/cellarium-cell-annotation-service-cas/) is a powerful, convenient way to assign cell types.
The simple kernel here demonstrates basic CAS-SCP plumbing.  The CAS [quickstart_tutorial.ipyb](https://github.com/cellarium-ai/cellarium-cas/blob/main/notebooks/quickstart_tutorial.ipynb), [repo](https://github.com/cellarium-ai/cellarium-cas), and [docs](https://cellarium-cas.readthedocs.io/) are useful resources.
The manual test below is especially optional, and mainly for reference.  Until we set up Google Secrets Manager (GSM) here, you'll need to use your own CAS API token.  It's easy to get, but turnaround might not be instant.
1. Get a CAS API token.  Visit …
=> Cell Annotation Service: proof of concept

ingest/ingest_pipeline.py, tests/test_ingest.py
This update fixes a bug in subsampling where a query to load the parent cluster group for setting association IDs (via `linear_data_id`) always returned the first clustering object.  Normally, this is not a problem as there is a 1:1 relationship between files and clustering objects, but AnnData files can have multiple.  As such, any user trying to extract multiple clusterings would always fail during subsampling.  Now, the query will correctly specify the clustering by name if the file is AnnData.
The simplest way to test this is to actually let ingest query your MongoDB instance.  Additionally, you will need the study_id and id of an AnnData file from your database.  To get this, you can open a Rails console session and run the following query (it doesn't matter if this a reference file …
=> Fix cluster query during AnnData subsampling (SCP-5140)

README.md, ingest/monitor.py, scripts/docker-compose-setup.sh, scripts/ingest-local-setup.sh, scripts/setup-mongo-dev.sh, scripts/vault-gsm-migration.sh
This replaces all existing Vault integration with Google Secrets Manager (GSM).  Similar to [this PR](https://github.com/broadinstitute/single_cell_portal_core/pull/2049) in `single_cell_portal_core`, a migration script has been added to copy relevant secrets out of Vault and into GSM.  However, since the aforementioned PR moved some of the required data already, this new migration script is agnostic and will allow the user to copy or roll back a single provided secret, rather than multiple hard-coded ones.  Additionally, all READMEs and local setup scripts for native Python or Docker have been updated to reference this new architecture.
1. If you are not authenticated into gcloud, run `gcloud auth login` and make sure you have your development SCP GCP project loaded:
```
gcloud info …
```
=> Replacing vault with GSM for local development (SCP-5716)

ingest/anndata_.py, scripts/sSCP395_h5ad_CAS.qmd, scripts/sSCP407_CAS_single.qmd, tests/test_anndata.py
A typo in AnnData extraction caused numeric metadata to be assigned TYPE `group` on AnnData metadata fragment extraction. This PR fixes the error and adds an automated test to ensure that numeric TYPE assignment occurs correctly.
Additionally, two quarto files are included for reference on CAS processing:
-  `sSCP395_h5ad_CAS.qmd`, includes running individual cell type calls and generation of clustering files with resulting CAS labels (after generating an h5ad file from component sSCP395 "classic" SCP files)
- `sSCP407_CAS_single.qmd`, runs CAS individual and cluster cell type calling and then sets scores to a numeric dtype in the AnnData object.
This work ensures that the AnnData from `sSCP407_CAS_single.qmd` can be used to visualizate CAS scores as continuous data.
1. Initialize your …
=> Ensure numeric metadata in adata.obs are assigned TYPE numeric in metadata fragment files

.github/workflows/minify_ontologies.yml, ingest/anndata_.py, ingest/cell_metadata.py, ingest/cli_parser.py, ingest/clusters.py, ingest/de.py, ingest/ingest_files.py, ingest/ingest_pipeline.py, ingest/mongo_connection.py, ingest/validation/metadata_validation.py, ingest/validation/validate_metadata.py, tests/test_de.py
This update adds pairwise DE to ingest pipeline. A new `--differential-expression` ingest pipeline parameter, `--de-type` is instantiated as "rest" by default, allowing existing "one vs rest" invocations to remain unchanged. Pairwise invocations add two additional parameters `--group1` and `--group2`. ~~Scanpy's rank_genes_groups function will accept a list of annotation values for "--group1", while we won't be taking advantage of that capability, it does require `--group1` to be passed as a list~~. Both `--group1` and `--group2` ~~is~~ passed as ~~a simple~~ string.
Testing using ingest_pipeline CLI requires an AnnData file and cluster & metadata AnnData fragments extracted from the AnnData file. 
1. Download the following files (you may already have them from PR#372): …
=> Enable pairwise DE in ingest pipeline (SCP-5766)

scripts/docker-compose-setup.sh
Similar to https://github.com/broadinstitute/single_cell_portal_core/pull/2187, this updates any `gcloud` commands that used Container Registry to now use Artifact Registry.  This is part of the mandatory switchover that must be completed by the end of March 2025.
1. Ensure Docker is running
2. Go to the project directory and run the `docker-compose-setup.sh` script, confirming you are left inside the running Docker container:
```
$ scripts/docker-compose-setup.sh 
...
Listing items under project broad-singlecellportal-staging, location us, repository gcr.io.
704fa3f: Pulling from broad-singlecellportal-staging/scp-ingest-pipeline-development
Digest: sha256:004e30bb0c98e31f17e707ac2a391f8ce320823d3bbde568db534c739013d32f
Status: Image is up to date for …
```
=> Update docker-compose-setup.sh to use GAR (SCP-5153)

ingest/de.py, ingest/monitor.py, scripts/vault-gsm-migration.sh
This update adds a logging handler for `STDOUT` to supplement the existing logging for ingest processes.  By adding this, we will leverage the existing integration of cloud logging into Batch API jobs.  This will add much greater visibility for jobs as we will not need to rely on the log file being delocalized back to the bucket.  This benefits running jobs the most as we will get real-time log messages, allowing us to debug the state of a job without waiting for completion.
Note: This also contains an unrelated update to the `vault-gsm-migration.sh` script that was needed to help import secrets from Vault into GSM better.
1. Initialize your environment as normal and run the following command from the `ingest` folder:
```
python ingest_pipeline.py --study-id 5d276a50421aa9117c982845 …
```
=> Add STDOUT logging handler for Cloud Logging integration (SCP-5902)

ingest/cli_parser.py, ingest/de.py, ingest/ingest_pipeline.py, tests/test_anndata.py, tests/test_ingest.py
Previously when a user enters an incorrect obsm_key, AnnData ingest failed with a KeyError, resulting in “Unexpected exit status 1”.  With the switch Batch API, the KeyError messaging is swallowed entirely, obscuring the cause of the failure for the study owner and makes troubleshooting take longer for an SCP admin.
1. Set up for ingest testing as per usual (from ingest directory, run source ../scripts/setup-mongo-dev.sh)
2. Run the following ingest pipeline job:
`python ingest_pipeline.py --study-id 5d276a50421aa9117c982845 --study-file-id 5dd5ae25421aa910a723a337 ingest_anndata --extract "['cluster']" --ingest-anndata --anndata-file ../tests/data/anndata/anndata_test.h5ad --obsm-keys "['foo']"`
3. Confirm that user.log contains
> Unable to extract cluster data from anndata file. Please …
=> Handle invalid obsm keys with actionable error message
