.circleci/config.yml, README.md, ingest/parallel_processing_ingest_dense_matrix.py, ingest/zarr_ingest.py, requirements.txt
This measure code coverage and reports metrics via [Codecov](https://codecov.io/gh/broadinstitute/scp-ingest-pipeline).  The new coverage badge is a public signal of code quality.  Codecov will also now comment in PRs with a report of how coverage changed in the code under review.
This partly satisfies SCP-1809.
=> Report code coverage metrics (SCP-1809)

ingest/ingest_files.py, ingest/ingest_pipeline.py, tests/mock_data/dense_matrix_19_genes_100k_cells_txt/gene_model_0.txt, tests/mock_data/matrix_mtx/gene_model_0.txt
Status codes for ingesting genes were not being returned. This PR is a bug fix for that issue.
=> Fix return status for ingesting genes

ingest/annotations.py, ingest/cell_metadata.py, ingest/clusters.py, ingest/dense.py, ingest/expression_files.py, ingest/ingest_files.py, ingest/ingest_pipeline.py, ingest/subsample.py, ingest/validation/validate_metadata.py, tests/test_subsample.py
Ingest pipeline was run through with some [representative data]( gs://broad-singlecellportal-staging-testing-data/) of existing SCP studies that are "known goods". This ensure that Ingest will run under normal usage. Please take note that subsampling is not covered but will be in [this branch](https://github.com/broadinstitute/single_cell_portal_core/tree/jb-ingest-subsampling).  Further testing is outline the [SCP backlog](https://broadworkbench.atlassian.net/browse/SCP-2026)
=> Test more data for Ingest Pipeline

ingest/ingest_pipeline.py, ingest/subsample.py
This PR fixes bugs dealing with subsampling. Particularly:
- Subsampling at all possible thresholds ([SCP-2036](https://broadworkbench.atlassian.net/browse/SCP-2036))
- Iterating through bins properly to avoid division by 0 ([SCP-2037](https://broadworkbench.atlassian.net/browse/SCP-2037) and [SCP-2038](https://broadworkbench.atlassian.net/browse/SCP-2038))
=> Ea fix subsample

ingest/make_toy_data.py
This trivially prevents duplicate gene names in matrices output by `make_toy_data.py`, which avoids validation errors in Ingest Pipeline.
The `awk` and `uniq -d` output below verifies that all rows in the first column (i.e. all gene names) are unique.
> (env) wm10d-4e7:ingest eweitz$ time python3 make_toy_data.py --num-files=1 --num-cells=1_000_000 --num-genes=10_000; mv AB_toy_data_toy.txt toy_dense_matrix_1M_cells_10K_genes.txt; ls -latrh toy_dense_matrix_1M_cells_10K_genes.txt; wc -l toy_dense_matrix_1M_cells_10K_genes.txt; awk -F '\t' '{print $1}' toy_dense_matrix_1M_cells_10K_genes.txt > genes_toy_data.txt; uniq -d genes_toy_data.txt
<details>
<summary>Output</summary>
```
Getting gene list
Fetching GTFs
Reading cached gzipped Homo_sapiens.GRCh38.100.gtf.gz
Returning content for …
```
=> Prevent duplicate gene names in toy matrix (SCP-2496)

setup.py
Update setup.py to enable push of 1.3.9 release to PyPI
This is in support of SCP-2414 (getting single-cell-portal published to PyPI).
=> increment PyPI version to 1.3.9

.pre-commit-config.yaml, setup.py
Increment PyPI package version so latest ingest pipeline release is available for manage-study.
This supports SCP-2598
=> Increment PyPI package version

ingest/expression_files/expression_files.py
The collection name is missing an 's'
=> Change collection name

ingest/expression_files/dense_ingestor.py
=> Ea add cells

setup.py
Incrementing package version to push latest ingest release to PyPI to support manage-study in single-cell-portal repo.
This supports SCP-2661.
=> Increment package version for PyPI

ingest/expression_files/mtx.py
Thei PR implements the comments in a prior PR that were not addressed.
=> * SCP-2900 Add comments from peer review

ingest/mongo_connection.py, tests/test_expression_files.py
This PR is an experimental solution to the batch op errors. The solution uses exponential back opp to retry inserting documents into Mongo.
=> * SCP-2904 Implement exponential backoff for BulkWriteError

ingest/expression_files/expression_files.py, ingest/mongo_connection.py, tests/mock_data/expression/dense_matrices/raw_counts_human_5k_cells_80_genes.py, tests/test_expression_files.py
This PR is meant to be tested in staging. If the PR checks out, reviews will be requested.
=> Ea fix raw counts

ingest/expression_files/expression_files.py, ingest/mongo_connection.py, tests/test_expression_files.py
Raw count matrices usually have the same cell names as processed matrices (i.e., matrices derived from said raw matrix). This PR fixes how Ingest Pipeline compares duplicate cell values.
=> * SCP-2949 Fix Raw counts

ingest/expression_files/expression_files.py, ingest/mongo_connection.py, tests/test_expression_files.py
#183 Wasn't merged into master. This is an attempt to do so.
=> Try and reset file (SCP-2949)

ingest/ingest_pipeline.py
Quick fix for getting the user unblocked, we probably want a more robust change to pandas config later.
=> stripping potential pandas-added whitespace for unique cell check

setup.py
Updating `setup.py` for releasing new version of `scp-ingest-pipeline` Docker image and publishing to PyPI.
=> Updating setup.py for 1.11.0 release (SCP-3414)

README.md
When setting up this repo on my local I ran into a couple issues and figured it might be helpful to note them here (like we do for SCP-core set up) to potentially help troubleshoot the same issues in the future for new folks.
=> Adding a trouble shooting section for setup (SCP-4236)

ingest/ingest_pipeline.py
The theory was good, but there are a lot of edges to need to be worked out (and test cases built) before this improved exception handling is ready for production.
=> Reverting general try-except (SCP-4279)

ingest/author_de.py, requirements.txt
This incorporates an upstream security patch, #316.
Given staffing, per [compliance discussion](https://broadinstitute.slack.com/archives/CADU7L0SZ/p1687532450858819?thread_ts=1687464810.060679&cid=CADU7L0SZ), we can merge after 1 approval, then get a 2nd review when next reviewer returns.
=> Release 1.27.3

README.md
This renames the master branch to main and replaces any references with the new name.  This does not have any affect on CI/CD, as neither CircleCI nor Google Cloud Build have any triggers based dependent on that branch name.  The only change is the link to the CodeCov status badge.
You will need to run the following commands to update your local repository:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> Renaming master branch to main (SCP-3346)
